### ISSUE TITLE
Support for array / object parameters

### ISSUE THREAD

**Issue by augustuswm** [oxidecomputer/progenitor#268]
We currently attempt to call `.to_string` on query argument values when constructing requests, but this fails on structures that don't implement display (i.e. Vec):
```json
{
  "in": "query",
  "name": "include",
  "schema": {
    "type": "array",
    "items": {
      "type": "string",
      "enum": [
        "custom_fields"
      ]
    }
  }
}
```
This results in a generated client that fails to compile.

The `query` method on `reqwest::RequestBuilder` accepts `T: Serialize`, but due to using `serde urlencoded` internally it isn't able to support `Vec<T>` by default either. The reasoning behind is a lack of specification for how they should be handled (https://github.com/seanmonstar/reqwest/issues/1079#issuecomment-741206109, https://github.com/nox/serde_urlencoded/issues/52).

The Open API spec does allow for array types though in query parameters (https://spec.openapis.org/oas/v3.0.3#parameter-locations). The serialization format is defined via the `style` and `explode` fields.

**Comment by ahl** [comment]
I think this was fixed by https://github.com/oxidecomputer/typify/pull/145 (and updating to use it); can you please give it a try?

**Comment by augustuswm** [comment]
I believe this is still an issue, This issue is for the case where we are trying to serialize a query parameter that can appear multiple times (or more specifically be given multiple values in a single request). The default case would be a query like: `?color=blue&color=black&color=brown`, (corresponding to `style: form` `explode: true`), but the Open API spec allows for a number of variations as to how the parameter gets serialized. I should have linked the [examples](https://spec.openapis.org/oas/v3.0.3#style-examples) originally, they show the full range of options.

I meant to put in some time to implement this, but ended up being focused on a few other things. I'll try to get back to this.

**Comment by azjezz** [comment]
I Just faced the same problem, so i decided to go with this really nasty fix: https://github.com/carthage-software/rust-sdk/blob/main/generator/src/main.rs#L1-L94

This however would only work for my case, as the server is written in PHP, the array query parameters have to end with `[]`, which makes it easy to detect them, if this was not the case, i don't know how i would have worked around it 😅

**Comment by jplatte** [comment]
Hey, I have a fork of `serde_urlencoded` that supports your use case: [`serde_html_form`](https://docs.rs/serde_html_form/latest/serde_html_form/)

**Comment by augustuswm** [comment]
That is really cool. I'll take a look and see if we might be able to apply it.
